# -*- coding: utf-8 -*-
"""ModNumpy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RqcTNFXYle49H6qb_zWYiVpvUIEBaOw6
"""

import numpy as np
from collections import Counter

nd_array = np.linspace(0, 6, 12, endpoint=False).reshape(3, 4)
nd_array[2:4]
nd_array[:2, 2]

mystery = np.array([[-13586,  15203,  28445, -27117,  -1781, -17182, -18049],
       [ 25936, -30968,  -1297,  -4593,   6451,  15790,   7181],
       [ 13348,  28049,  28655,  -6012,  21762,  25397,   8225],
       [ 13240,   7994,  32592,  20149,  13754,  11795,   -564],
       [-21725,  -8681,  30305,  22260, -17918,  12578,  29943],
       [-16841, -25392, -17278,  11740,   5916,    -47, -32037]],
      dtype=np.int16)

elem_5_3 = mystery[4, 2]
print(elem_5_3)

mystery.shape

last = mystery[5, 6]
print(last)

line = mystery[3:4]
line_4 = line[0]
print(line_4)

col = mystery[0:, 5:6]
col_1 = col.transpose()
col_2 = col_1[0]
print(col_2)

part = mystery[1:4, 2:5]
print(part)

r = mystery[0:, 6:7]
r = r[::-1]
re = r.transpose()
rev = re[0]
print(rev)

trans = mystery.transpose()
print(trans)

arr = np.array([23,12,45,12,23,4,15,3])

arr_new = np.sort(arr)
print(arr)
print(arr_new)

print(arr.sort())

print(arr)

data = np.array([4, 9, -4, 3])

roots = np.sqrt(data)
np.isnan(roots)
roots[np.isnan(roots)] = 0
print(roots)
sum(roots)

"""Задание 7.4"""

mystery1 = np.array([ 12279., -26024.,  28745.,  np.nan,  31244.,  -2365.,  -6974.,
        -9212., np.nan, -17722.,  16132.,  25933.,  np.nan, -16431.,
        29810.], dtype=np.float32)
nans_index = np.isnan(mystery1)
nans_index

c = Counter(nans_index)
n_nan = c[True]
n_nan

mystery_new = mystery1
mystery_new[np.isnan(mystery_new)] = 0

mystery_int = np.int32(mystery1)
array = np.sort(mystery1)
print(mystery_int)
print(array)

table = array.reshape((5, 3), order='F')
table

c = table[0:, 1:2]
co = c.transpose()
col = co[0]
print(col)